# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ mkDerivation, network, tls, crypto-random, data-default, base, pop3-client, stdenv }:

mkDerivation {
  pname = "pop3s-client";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ network tls crypto-random data-default base pop3-client ];
  description = "pop3s protocol";
  license = stdenv.lib.licenses.mit;
}
